import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { supabase } from './supabaseClient';
import { Car, Building2, CalendarDays, CreditCard, FileText, LogOut, Menu, Plus, Search, Trash2, Edit3, MapPin, Phone, ChevronRight, Wrench, BarChart3, Users, CheckCircle2, Clock3 } from 'lucide-react';
import './styles.css';

const VERSION = 'TallerSmart Real MVP v7.0';
const fmt = (n) => Number(n || 0).toLocaleString('es-AR', { style:'currency', currency:'ARS', maximumFractionDigits:0 });
const plateNorm = (p) => (p || '').toUpperCase().replace(/\s|-/g, '');

function App(){
  const [session,setSession]=useState(null);
  const [view,setView]=useState('home');
  const [workshop,setWorkshop]=useState(null);
  const [loading,setLoading]=useState(true);
  useEffect(()=>{ supabase.auth.getSession().then(({data})=>{setSession(data.session); setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s)}); return()=>subscription.unsubscribe();},[]);
  useEffect(()=>{ if(session) loadWorkshop(session.user.id); else setWorkshop(null); },[session]);
  async function loadWorkshop(uid){ const {data}=await supabase.from('workshops').select('*').eq('owner_id',uid).maybeSingle(); if(data){setWorkshop(data);setView('admin')} }
  async function signOut(){ await supabase.auth.signOut(); setView('home'); }
  if(loading) return <Shell><p>Cargando...</p></Shell>;
  return <Shell>{view==='home'&&<Home setView={setView}/>} {view==='login'&&<WorkshopLogin setView={setView} onReady={(w)=>{setWorkshop(w);setView('admin')}}/>} {view==='register'&&<WorkshopRegister setView={setView}/>} {view==='plate'&&<ClientPlate signOut={()=>setView('home')}/>} {view==='admin'&& session && workshop && <AdminDashboard workshop={workshop} signOut={signOut}/>}</Shell>;
}
function Shell({children}){return <div className="app">{children}</div>}
function Home({setView}){return <div className="home"><img src="/logo.png" className="logo"/><h1>TallerSmart</h1><p className="desc">TallerSmart centraliza el historial vehicular entre talleres y clientes, permitiendo trazabilidad, pagos y seguimiento inteligente del mantenimiento.</p><button className="big" onClick={()=>setView('login')}><Building2/><span><b>Ingresar como Taller</b><small>Gestioná tu taller y clientes</small></span><ChevronRight/></button><button className="big" onClick={()=>setView('plate')}><Car/><span><b>Ingresar con Patente</b><small>Consultá el historial de tu vehículo</small></span><ChevronRight/></button><section className="features"><h2>¿Qué ofrece TallerSmart?</h2><div><Feature icon={<FileText/>} t="Historial" d="Accedé al historial completo."/><Feature icon={<CreditCard/>} t="Pagos" d="Pagos y comprobantes."/><Feature icon={<Wrench/>} t="Mantenimiento" d="Seguimiento inteligente."/><Feature icon={<Users/>} t="Conexión" d="Talleres y clientes conectados."/></div></section><footer>{VERSION}</footer></div>}
function Feature({icon,t,d}){return <article>{icon}<b>{t}</b><small>{d}</small></article>}
function WorkshopLogin({setView,onReady}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('');async function login(){setMsg('Ingresando...');const {data,error}=await supabase.auth.signInWithPassword({email,password}); if(error){setMsg(error.message);return} const pending=JSON.parse(localStorage.getItem('pendingWorkshop')||'null'); let {data:ws}=await supabase.from('workshops').select('*').eq('owner_id',data.user.id).maybeSingle(); if(!ws && pending){const {data:newWs,error:e}=await supabase.from('workshops').insert({...pending,owner_id:data.user.id,email:data.user.email,confirmed:true}).select().single(); if(e){setMsg(e.message);return} localStorage.removeItem('pendingWorkshop'); ws=newWs;} if(!ws){setMsg('Ingresaste, pero falta registrar los datos del taller.');return} onReady(ws)} return <AuthCard title="Ingreso Taller"><input placeholder="Correo electrónico" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Contraseña" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={login}>Ingresar</button><p>{msg}</p><button className="link" onClick={()=>setView('register')}>Registrar taller</button><button className="link" onClick={()=>setView('home')}>Volver</button></AuthCard>}
function WorkshopRegister({setView}){const [f,setF]=useState({name:'',email:'',phone:'',address:'',opening_hours:'',mercadopago_alias:'',modo_alias:'',password:''});const [msg,setMsg]=useState('');const set=(k,v)=>setF({...f,[k]:v});async function reg(){setMsg('Creando cuenta...'); localStorage.setItem('pendingWorkshop',JSON.stringify({name:f.name,phone:f.phone,address:f.address,opening_hours:f.opening_hours,mercadopago_alias:f.mercadopago_alias,modo_alias:f.modo_alias})); const {error}=await supabase.auth.signUp({email:f.email,password:f.password}); if(error){setMsg(error.message);return} setMsg('Cuenta creada. Si Supabase pide confirmación, revisá tu correo. Luego iniciá sesión.');} return <AuthCard title="Registrar nuevo taller"><input placeholder="Nombre del taller" onChange={e=>set('name',e.target.value)}/><input placeholder="Correo electrónico" onChange={e=>set('email',e.target.value)}/><input placeholder="Teléfono / WhatsApp" onChange={e=>set('phone',e.target.value)}/><input placeholder="Dirección" onChange={e=>set('address',e.target.value)}/><input placeholder="Horario de atención" onChange={e=>set('opening_hours',e.target.value)}/><input placeholder="Alias Mercado Pago" onChange={e=>set('mercadopago_alias',e.target.value)}/><input placeholder="Alias MODO" onChange={e=>set('modo_alias',e.target.value)}/><input placeholder="Contraseña" type="password" onChange={e=>set('password',e.target.value)}/><button onClick={reg}>Crear cuenta</button><p>{msg}</p><button className="link" onClick={()=>setView('login')}>Ya tengo cuenta</button></AuthCard>}
function AuthCard({title,children}){return <div className="auth"><img src="/logo.png"/><h2>{title}</h2>{children}</div>}

function AdminDashboard({workshop,signOut}){const [menu,setMenu]=useState(false);const [section,setSection]=useState('panel');const [clients,setClients]=useState([]);const [jobs,setJobs]=useState([]);const [appointments,setAppointments]=useState([]);const [selected,setSelected]=useState(null);useEffect(()=>{loadAll()},[]);async function loadAll(){const {data:c}=await supabase.from('clients').select('*, vehicles(*)').eq('workshop_id',workshop.id).order('created_at',{ascending:false});setClients(c||[]);const {data:j}=await supabase.from('jobs').select('*, vehicles(*), clients(name), workshops(name,address,phone,opening_hours)').eq('workshop_id',workshop.id).order('job_date',{ascending:false});setJobs(j||[]);const {data:a}=await supabase.from('appointments').select('*, vehicles(*), clients(name)').eq('workshop_id',workshop.id).order('appointment_date',{ascending:true});setAppointments(a||[]);}return <div className="dash"><header><button className="icon" onClick={()=>setMenu(!menu)}><Menu/></button><div><b>{workshop.name}</b><small>Panel de taller</small></div><button className="icon" onClick={signOut}><LogOut/></button></header>{menu&&<nav className="drawer"><button onClick={()=>{setSection('clients');setMenu(false)}}>Clientes</button><button onClick={()=>{setSection('jobs');setMenu(false)}}>Trabajos realizados</button><button onClick={()=>{setSection('billing');setMenu(false)}}>Facturación</button><button onClick={()=>{setSection('turns');setMenu(false)}}>Turnos</button></nav>} {section==='panel'&&<Panel clients={clients} jobs={jobs} appointments={appointments} setSection={setSection}/>} {section==='clients'&&<Clients clients={clients} workshop={workshop} reload={loadAll} selected={selected} setSelected={setSelected}/>} {section==='jobs'&&<Jobs jobs={jobs}/>} {section==='billing'&&<Billing jobs={jobs}/>} {section==='turns'&&<Turns workshop={workshop} clients={clients} appointments={appointments} reload={loadAll}/>}<footer>{VERSION}</footer></div>}
function Panel({clients,jobs,appointments,setSection}){const pending=jobs.filter(j=>j.payment_status!=='paid').length;return <main><div className="stats"><Stat n={clients.length} t="Clientes"/><Stat n={pending} t="Pagos pendientes"/><Stat n={jobs.length} t="Trabajos"/><Stat n={appointments.length} t="Turnos"/></div><div className="cards"><button onClick={()=>setSection('clients')}>Gestionar clientes</button><button onClick={()=>setSection('jobs')}>Ver trabajos</button><button onClick={()=>setSection('billing')}>Facturación</button><button onClick={()=>setSection('turns')}>Turnos</button></div></main>}
function Stat({n,t}){return <div className="stat"><b>{n}</b><small>{t}</small></div>}
function Clients({clients,workshop,reload,selected,setSelected}){const [mode,setMode]=useState('menu');const [q,setQ]=useState('');const shown=clients.filter(c=>(c.name+c.vehicles?.plate).toLowerCase().includes(q.toLowerCase()));return <main>{mode==='menu'&&<div className="cards"><button onClick={()=>setMode('new')}><Plus/>Nuevo cliente</button><button onClick={()=>setMode('search')}><Search/>Buscar cliente</button></div>}{mode==='new'&&<ClientForm workshop={workshop} reload={()=>{reload();setMode('search')}}/>}{mode==='search'&&<><input placeholder="Buscar por patente o cliente" value={q} onChange={e=>setQ(e.target.value)}/>{shown.map(c=><div className="item" key={c.id} onClick={()=>setSelected(c)}><b>{c.name}</b><small>{c.vehicles?.plate} · {c.vehicles?.brand} {c.vehicles?.model}</small></div>)}{selected&&<ClientDetail client={selected} workshop={workshop} reload={reload}/>}</>}<button className="link" onClick={()=>setMode('menu')}>Volver a Clientes</button></main>}
function ClientForm({workshop,reload}){const [f,setF]=useState({name:'',phone:'',email:'',plate:'',brand:'',model:'',year:'',current_km:''});const [msg,setMsg]=useState('');const set=(k,v)=>setF({...f,[k]:v});async function save(){setMsg('Guardando...'); const plate=plateNorm(f.plate); let {data:v}=await supabase.from('vehicles').select('*').eq('plate',plate).maybeSingle(); if(!v){const res=await supabase.from('vehicles').insert({plate,brand:f.brand,model:f.model,year:f.year||null,current_km:f.current_km||0}).select().single(); if(res.error){setMsg(res.error.message);return} v=res.data;} const {error}=await supabase.from('clients').insert({workshop_id:workshop.id,vehicle_id:v.id,name:f.name,phone:f.phone,email:f.email}); if(error){setMsg(error.message);return} setMsg('Cliente guardado'); reload();}return <div className="form"><h3>Nuevo cliente</h3>{['name','phone','email','plate','brand','model','year','current_km'].map(k=><input key={k} placeholder={k} onChange={e=>set(k,e.target.value)}/>)}<button onClick={save}>Guardar cliente</button><p>{msg}</p></div>}
function ClientDetail({client,workshop,reload}){const [edit,setEdit]=useState(false);const [name,setName]=useState(client.name);const [work,setWork]=useState({title:'',description:'',km:client.vehicles?.current_km||0,cost:''});async function del(){if(!confirm('¿Eliminar cliente?'))return; await supabase.from('clients').delete().eq('id',client.id); reload()}async function upd(){await supabase.from('clients').update({name}).eq('id',client.id);setEdit(false);reload()}async function addJob(){await supabase.from('jobs').insert({workshop_id:workshop.id,vehicle_id:client.vehicle_id,client_id:client.id,title:work.title,description:work.description,km:work.km,cost:work.cost||0,payment_status:'pending'}); reload(); alert('Trabajo cargado')}return <div className="detail"><h3>{client.name}</h3>{edit?<><input value={name} onChange={e=>setName(e.target.value)}/><button onClick={upd}>Guardar edición</button></>:<button onClick={()=>setEdit(true)}><Edit3/>Editar cliente</button>}<button className="danger" onClick={del}><Trash2/>Eliminar cliente</button><h3>Cargar trabajo</h3><input placeholder="Trabajo" onChange={e=>setWork({...work,title:e.target.value})}/><textarea placeholder="Detalle" onChange={e=>setWork({...work,description:e.target.value})}/><input placeholder="Km" type="number" onChange={e=>setWork({...work,km:e.target.value})}/><input placeholder="Costo" type="number" onChange={e=>setWork({...work,cost:e.target.value})}/><button onClick={addJob}>Agregar al historial</button></div>}
function Jobs({jobs}){return <main><h2>Trabajos realizados</h2>{jobs.map(j=><div className="item" key={j.id}><b>{j.title}</b><small>{j.clients?.name||'Cliente'} · {j.vehicles?.plate} · {fmt(j.cost)} · {j.payment_status==='paid'?'Pago acreditado':'Pendiente'}</small><p>{j.description}</p></div>)}</main>}
function Billing({jobs}){const total=jobs.reduce((a,j)=>a+Number(j.cost||0),0), paid=jobs.filter(j=>j.payment_status==='paid').reduce((a,j)=>a+Number(j.cost||0),0);return <main><h2>Facturación</h2><div className="stats"><Stat n={fmt(total)} t="Total trabajos"/><Stat n={fmt(paid)} t="Cobrado"/><Stat n={fmt(total-paid)} t="Pendiente"/></div><Jobs jobs={jobs}/></main>}
function Turns({workshop,clients,appointments,reload}){const [f,setF]=useState({client_id:'',title:'',appointment_date:'',notes:''});async function save(){const c=clients.find(x=>x.id===f.client_id); if(!c)return; await supabase.from('appointments').insert({workshop_id:workshop.id,client_id:c.id,vehicle_id:c.vehicle_id,title:f.title,appointment_date:f.appointment_date,notes:f.notes}); reload()}return <main><h2>Turnos</h2><div className="form"><select onChange={e=>setF({...f,client_id:e.target.value})}><option>Seleccionar cliente</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name} - {c.vehicles?.plate}</option>)}</select><input placeholder="Motivo" onChange={e=>setF({...f,title:e.target.value})}/><input type="datetime-local" onChange={e=>setF({...f,appointment_date:e.target.value})}/><textarea placeholder="Notas" onChange={e=>setF({...f,notes:e.target.value})}/><button onClick={save}>Asignar turno</button></div>{appointments.map(a=><div className="item" key={a.id}><b>{new Date(a.appointment_date).toLocaleString('es-AR')}</b><small>{a.clients?.name} · {a.vehicles?.plate} · {a.title}</small></div>)}</main>}
function ClientPlate({signOut}){const [plate,setPlate]=useState('');const [vehicle,setVehicle]=useState(null);const [jobs,setJobs]=useState([]);const [msg,setMsg]=useState('');async function search(){setMsg('Buscando...');setVehicle(null);setJobs([]);const {data:v}=await supabase.from('vehicles').select('*').eq('plate',plateNorm(plate)).maybeSingle(); if(!v){setMsg('No encontramos historial para esa patente.');return} setVehicle(v); const {data:j}=await supabase.from('jobs').select('*, workshops(name,address,phone,opening_hours)').eq('vehicle_id',v.id).order('job_date',{ascending:false}); setJobs(j||[]);setMsg('');}async function pay(job){await supabase.from('jobs').update({payment_status:'paid'}).eq('id',job.id);search()}return <main className="client"><button className="link" onClick={signOut}>Volver</button><h2>Ingresar con patente</h2><input placeholder="Ej: AB123CD" value={plate} onChange={e=>setPlate(e.target.value)}/><button onClick={search}>Consultar historial</button><p>{msg}</p>{vehicle&&<div className="vehicle"><Car/><h3>{vehicle.plate}</h3><p>{vehicle.brand} {vehicle.model} {vehicle.year||''}</p></div>}{jobs.map(j=><div className="job" key={j.id}><h3>{j.title}</h3><p>{j.description}</p><small>{new Date(j.job_date).toLocaleDateString('es-AR')} · {j.km||0} km · {fmt(j.cost)}</small><div className={j.payment_status==='paid'?'paid':'pending'}>{j.payment_status==='paid'?<><CheckCircle2/> Pago acreditado</>:<><Clock3/> Pendiente de pago</>}</div>{j.payment_status!=='paid'&&<button onClick={()=>pay(j)}><CreditCard/> Pagar demo</button>}<details><summary>Datos del taller</summary><p><b>{j.workshops?.name}</b></p><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(j.workshops?.address||'')}`} target="_blank"><MapPin/> Google Maps</a><a href={`https://wa.me/${(j.workshops?.phone||'').replace(/\D/g,'')}`} target="_blank"><Phone/> WhatsApp</a><p>{j.workshops?.opening_hours}</p></details></div>)}<footer>{VERSION}</footer></main>}

createRoot(document.getElementById('root')).render(<App/>);
